baseURL = 'https://patchless.netlify.app/'
languageCode = 'en-us'
title = "Patchless"

paginate = 10


[params]
description = "Writeups for CTF, Leetcode and other things CS related"
dateFormat = "2 Jan, 2006"


[taxonomies]

category = "categories"
